package constantes.web.fnext.n2;

public interface ComboN2 {

    String APROVADO = "APROVADO N2";
    String REPROVADO = "REPROVADO";
    String RETORNO_N1 = "RETORNO N1";

    String ERRO_OPERACIONAL = "ERRO OPERACIONAL";
    String FRAUDE_IDEOLOGICA = "FRAUDE IDEOLÓGICA";
    String AUTO_FRAUDE = "AUTO FRAUDE";
    String DADOS_INCONSISTENTES = "DADOS INCONSISTENTES";
    String DOCUMENTOS_ILEGIVEIS = "DOCUMENTOS ILEGÍVEIS";
    String DOCUMENTO_ILEGIVEL = "DOCUMENTO ILEGÍVEL";
    String DOCUMENTO_EMISSAO = "DOCUMENTO EMISSÃO ANTES DE 1984";

    String CONTAMINACAO_POR_FRAUDE = "CONTAMINAÇÃO POR FRAUDE";
    String CONTEXTO_DE_RISCOS = "CONTEXTO DE RISCOS";
    String DUAS_OU_MAIS_INCONSISTENCIAS = "DUAS OU MAIS INCONSISTÊNCIAS";
    String MULTIPLICIDAD_DE_CPF = "MULTIPLICIDADE DE CPF";


}
