package constantes.adesao.termosECondicoes;

public interface TermosECondicoes {

    String TERMO_PROPOSTA_DE_ABERTURA_DE_CONTA = "Proposta de Abertura de Conta";
    String[] CONDICOES_PROPOSTA_DE_ABERTURA_DE_CONTA = {"FICHA-PROPOSTA DE ABERTURA DE CONTA DE DEPÓSITOS - PESSOA FÍSICA"};

    String TERMO_INFORMACOES_ESSENCIAIS_CONTA_NEXT = "Informações Essenciais Conta Next";
    String[] CONDICOES_INFORMACOES_ESSENCIAIS_CONTA_NEXT = {"INFORMAÇÕES ESSENCIAIS CONTA NEXT"};

    String TERMO_TERMOS_E_CONDICOES_DE_USO_DO_APLICATIVO_NEXT = "Termos e Condições de Uso do Aplicativo Next";
    String[] CONDICOES_TERMOS_E_CONDICOES_DE_USO_DO_APLICATIVO_NEXT = {"TERMO DE ADESÃO E CONDIÇÕES DE USO DO APLICATIVO NEXT"};

    String TERMO_REGULAMENTO_DA_FUNCAO_CREDITO_DOS_CARTOES_NEXT = "Regulamento da Função Crédito dos Cartões Next";
    String[] CONDICOES_REGULAMENTO_DA_FUNCAO_CREDITO_DOS_CARTOES_NEXT = {"Regulamento da Função Crédito dos Cartões Next"};

    String TERMO_REGULAMENTO_DO_PROGRAMA_DE_FIDELIDADE_CARTOES_BRADESCO = "Regulamento do Programa de Fidelidade Cartões Bradesco - Cartão Next";
    String[] CONDICOES_REGULAMENTO_DO_PROGRAMA_DE_FIDELIDADE_CARTOES_BRADESCO = {"REGULAMENTO DO PROGRAMA DE FIDELIDADE CARTÕES BRADESCO - CARTÃO NEXT"};
}
